name: docs
channels:
dependencies:
  - python=3.8
  - pip
  - pip:
    - sphinx_rtd_theme==1.1.1
    - sphinx-autoapi
    - https://github.com/revitron/revitron-sphinx-theme/archive/refs/tags/0.7.0.zip
